---
---
### Computación científica y análisis de datos
---
#### EJEMPLO: Módulo Numpy

In [1]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
a1[0]

1

In [6]:
a2 = np.arange(5)
print(a2)
print(type(a2))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
a3 = np.full((3,4), 1.5, dtype=float)
print(a3)
print(type(a3))

[[1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5]]
<class 'numpy.ndarray'>
